// data.js — metadata for each solid: title, integral, description, constraints, camera
import {
  buildSolid1, buildSolid2A, buildSolid2B, buildSolid3,
  buildSolid4, buildSolid5, buildSolid6, buildSolid7,
  buildSolid8, buildSolid9
} from './solids.js';

export const SOLIDS = [
  {
    num: '#1', coord: 'Cilíndricas',
    title: 'Ext. cono · Int. cilindro',
    fullTitle: 'Exterior al cono, interior al cilindro',
    integral: '\\displaystyle\\iiint_S dV = \\int_{0}^{2\\pi}\\!\\int_{0}^{1}\\!\\int_{0}^{r} r\\,dz\\,dr\\,d\\theta',
    desc: 'Sólido sobre el plano XY, exterior a la hoja superior del cono z²=x²+y², interior al cilindro x²+y²=1.',
    constraints: ['x²+y² ≤ 1', 'z ≤ √(x²+y²)', 'z ≥ 0'],
    cam: { r:11, th:0.55, ph:0.68, py:1.2 },
    build: buildSolid1,
  },
  {
    num: '#2A', coord: 'Esféricas',
    title: 'Entre esferas · Fuera del cono',
    fullTitle: 'Sólido FUERA del cono, entre dos esferas',
    integral: '\\displaystyle\\iiint_S dV = \\int_{0}^{2\\pi}\\!\\int_{\\pi/4}^{3\\pi/4}\\!\\int_{1}^{3}\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta',
    desc: 'Entre las esferas ρ=1 y ρ=3, exterior al cono z²=x²+y² (φ=π/4). La región queda cerca del plano ecuatorial.',
    constraints: ['x²+y²+z² ≥ 1', 'x²+y²+z² ≤ 9', 'z² ≤ x²+y²', 'π/4 ≤ φ ≤ 3π/4'],
    cam: { r:10, th:0.55, ph:0.68, py:0 },
    build: buildSolid2A,
  },
  {
    num: '#2B', coord: 'Esféricas',
    title: 'Entre esferas · Dentro del cono',
    fullTitle: 'Sólido DENTRO del cono, entre dos esferas',
    integral: '\\displaystyle\\iiint_S dV = \\int_{0}^{2\\pi}\\!\\left(\\int_{0}^{\\pi/4}+\\int_{3\\pi/4}^{\\pi}\\right)\\!\\int_{1}^{3}\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta',
    desc: 'Entre las esferas ρ=1 y ρ=3, interior al cono z²=x²+y². Incluye dos napas (casquetes polar y antipodal).',
    constraints: ['x²+y²+z² ≥ 1', 'x²+y²+z² ≤ 9', 'z² ≥ x²+y²', 'φ∈[0,π/4] ∪ [3π/4,π]'],
    cam: { r:10, th:0.55, ph:0.68, py:0 },
    build: buildSolid2B,
  },
  {
    num: '#3', coord: 'Rectangulares',
    title: 'Sobre paraboloide 2r² · Bajo z=8',
    fullTitle: 'Interior al cilindro, sobre el paraboloide z=2r², bajo z=8',
    integral: '\\displaystyle\\iiint_S dV = \\int_{0}^{2}\\!\\int_{0}^{\\sqrt{4-x^2}}\\!\\int_{2x^2+2y^2}^{8}dz\\,dy\\,dx',
    desc: 'Primer cuadrante, interior al cilindro x²+y²=4, sobre el paraboloide z=2(x²+y²) y bajo el plano z=8.',
    constraints: ['x²+y² ≤ 4', 'z ≥ 2(x²+y²)', 'z ≤ 8', 'x≥0, y≥0'],
    cam: { r:13, th:0.6, ph:0.68, py:1.1 },
    build: buildSolid3,
  },
  {
    num: '#4', coord: 'Rectangulares',
    title: 'Primer octante · Planos oblicuos',
    fullTitle: 'Sólido en el primer octante entre planos oblicuos',
    integral: '\\displaystyle\\iiint_S dV = \\int_{4}^{8}\\!\\int_{0}^{\\frac{4-z}{2}}\\!\\int_{3-\\frac{3x}{2}}^{\\frac{3}{4}(8-z-2x)}dy\\,dx\\,dz',
    desc: 'Primer octante acotado por z=4, z=8, el plano 2x+(4/3)y=4 y el plano oblicuo 2x+(4/3)y+z=8.',
    constraints: ['x≥0, y≥0, z≥0', '4 ≤ z ≤ 8', '2x+(4/3)y ≥ 4', '2x+(4/3)y+z ≤ 8'],
    cam: { r:12, th:0.5, ph:0.65, py:1.8 },
    build: buildSolid4,
  },
  {
    num: '#5', coord: 'Cilíndricas',
    title: 'Cilindro desplazado · Esfera r=2',
    fullTitle: 'Interior al cilindro (x−1)²+y²=1, interior a la esfera, sobre z=0',
    integral: '\\displaystyle\\iiint_S dV = \\int_{-\\pi/2}^{\\pi/2}\\!\\int_{0}^{2\\cos\\theta}\\!\\int_{0}^{\\sqrt{4-r^2}}r\\,dz\\,dr\\,d\\theta',
    desc: 'Interior al cilindro desplazado (x−1)²+y²=1 (r=2cosθ), interior a la esfera x²+y²+z²=4 y sobre z=0.',
    constraints: ['(x−1)²+y² ≤ 1', 'x²+y²+z² ≤ 4', 'z ≥ 0'],
    cam: { r:10, th:0.4, ph:0.7, py:1 },
    build: buildSolid5,
  },
  {
    num: '#6', coord: 'Cilíndricas',
    title: 'Cilindro r=4 · Bajo plano 2z=y',
    fullTitle: 'Interior al cilindro r=4, sobre XY y bajo el plano inclinado z=y/2',
    integral: '\\displaystyle\\iiint_S dV = \\int_{0}^{\\pi}\\!\\int_{0}^{4}\\!\\int_{0}^{\\frac{r\\sin\\theta}{2}} r\\,dz\\,dr\\,d\\theta',
    desc: 'Interior al cilindro x²+y²≤16 (r≤4), sobre el plano XY (z≥0) y bajo 2z=y. Como z≥0 exige y≥0, el ángulo se restringe a θ∈[0,π].',
    constraints: ['r ≤ 4 (x²+y² ≤ 16)', 'z ≥ 0', 'z ≤ y/2', 'θ∈[0,π] por y≥0'],
    cam: { r:11, th:0.6, ph:0.7, py:1.2 },
    build: buildSolid6,
  },
  {
    num: '#7', coord: 'Rectangulares',
    title: 'Entre paraboloide y cilindro parabólico',
    fullTitle: 'Entre z=x²+y² y el cilindro parabólico z=5−y²',
    integral: '\\displaystyle\\iiint_S dV = \\int_{-\\sqrt{5}}^{\\sqrt{5}}\\!\\int_{-\\sqrt{\\frac{5-x^2}{2}}}^{\\sqrt{\\frac{5-x^2}{2}}}\\!\\int_{x^2+y^2}^{5-y^2}dz\\,dy\\,dx',
    desc: 'Sólido entre el paraboloide (abajo) z=x²+y² y el cilindro parabólico (arriba) z=5−y². Proyección en XY: elipse x²+2y²≤5.',
    constraints: ['z ≥ x²+y²', 'z ≤ 5−y²', 'x²+2y² ≤ 5'],
    cam: { r:11, th:0.55, ph:0.7, py:1.4 },
    build: buildSolid7,
  },
  {
    num: '#8', coord: 'Cilíndricas',
    title: 'Interior esfera √5 · Superior al cono z=r/2',
    fullTitle: 'Interior a la esfera x²+y²+z²=5 y superior al cono x²+y²=4z²',
    integral: '\\displaystyle\\iiint_S dV = \\int_{0}^{2\\pi}\\!\\int_{0}^{2}\\!\\int_{r/2}^{\\sqrt{5-r^2}} r\\,dz\\,dr\\,d\\theta',
    desc: 'Acotado superiormente por la esfera x²+y²+z²=5 e inferiormente por z=r/2 (cono x²+y²=4z²). Intersección en z=1, r=2.',
    constraints: ['x²+y²+z² ≤ 5', 'z ≥ r/2', 'z ≥ 0', 'r ≤ 2'],
    cam: { r:10, th:0.55, ph:0.68, py:1.2 },
    build: buildSolid8,
  },
  {
    num: '#9', coord: 'Esféricas',
    title: 'Ext. cono z=r/2 · Int. esfera (z−1)²+r²=1',
    fullTitle: 'Exterior al cono z=½r e interior a la esfera x²+y²+(z−1)²=1',
    integral: '\\displaystyle\\iiint_S dV = \\int_{0}^{2\\pi}\\!\\int_{\\arctan 2}^{\\pi/2}\\!\\int_{0}^{2\\cos\\phi}\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta',
    desc: 'Sólido interior a la esfera x²+y²+(z−1)²=1 (ρ=2cosφ en esféricas) y exterior al cono z=½√(x²+y²) (φ=arctan 2). Yace completamente sobre el plano XY.',
    constraints: ['x²+y²+(z−1)² ≤ 1', 'z ≤ ½√(x²+y²)', 'z ≥ 0', 'arctan(2) ≤ φ ≤ π/2'],
    cam: { r:9, th:0.55, ph:0.72, py:0.8 },
    build: buildSolid9,
  },
];
